### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by francen** [RattyDAVE/docker-ubuntu-hercules-mvs#1]
attempting to run container via instructions on RASPI 4B shows the following errors:

$ sudo docker logs tk4-
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by RattyDAVE** [comment]
This container is x86 based not arm (the Raspberry Pi). This is the reason to not working....

If you want I can provide instructions to build on the Pi.

I have a few Raspberry Pi's myself.. never thought of running docker on them.

**Comment by francen** [comment]
thank you RattyDAVE ... I've closed this issue as a "user problem" :)

**Comment by RattyDAVE** [comment]
User problem sounds a bit harsh.... 

I like that other people use what I have put together in way I have never thought of.
