### ISSUE TITLE
unable to connect to "mainframe" from other host on my lan

### ISSUE THREAD

**Issue by lemmy04** [RattyDAVE/docker-ubuntu-hercules-mvs#3]
I am unable to do a 3270 session from any other host than the one the container is on... if I try to run an x3270 session from any other host I get connection refused.

any ideas?

**Comment by lemmy04** [comment]
solved. the emulator doesn't speak IPv6, and x3270 doesn't have a "-4" option either - but my containerhost has a resolvable IPv6 address...

**Comment by RattyDAVE** [comment]
That's was a quick one.. lol

**Comment by lemmy04** [comment]
yup :) now I just need to find something to DO with my new "mainframe" ;)

**Comment by RattyDAVE** [comment]
Ah... I know that feeling!

**Comment by lemmy04** [comment]
actually, d'oh. forgot to specify the port. "x3270 dockerhost 3270" works fine just from anywhere...

on the other hand, why would "x3270 hostname" without the port work, if the container is on the same host, but not if it's on a different host?

**Comment by RattyDAVE** [comment]
what is the client you are using? I am guessing x3270 in a linux distro. 

That is to do with your network config. Docker container ares are only exposed externally via the EXPOSE part.

**Comment by lemmy04** [comment]
> 
> 
> yup :) now I just need to find something to DO with my new "mainframe" ;)

for now i've been playing adventure. ALMOST as good as zork 1... XD
