### ISSUE TITLE
feedback, sort of :)

### ISSUE THREAD

**Issue by lemmy04** [RattyDAVE/docker-ubuntu-hercules-mvs#5]
You might find https://www.tuxonline.tech/index.php/2021/04/16/from-0-to-kubernetes-and-now-for-something-completely-different/ a bit entertaining :)

**Comment by lemmy04** [comment]
You might find https://www.tuxonline.tech/index.php/2021/04/16/from-0-to-kubernetes-and-now-for-something-completely-different/ a bit entertaining :)

**Comment by RattyDAVE** [comment]
“Pretty awesome guy, Old and cool” – Well that about sums me up!

Thank you very much for the blog post. It is appreciated greatly!

Regards!

RattyDAVE
“Pretty awesome guy, Old and cool”  - lemmy04

**Comment by lemmy04** [comment]
The "old and cool" referred to the stuff in your docker images, but if you feel it describes you well and you're not offended... :)

**Comment by RattyDAVE** [comment]
I am taking that and running with it.. LOL

**Comment by lemmy04** [comment]
if you happen to have telegram on your phone, feel free to talk to @ll_frotzbot ...

**Comment by RattyDAVE** [comment]
@ll_frotzbot on telegram... that is cool!

**Comment by lemmy04** [comment]
..and also on my blog in the kubernetes series...

**Comment by lemmy04** [comment]
oh, if the game you choose annoys you with ***MORE*** prompts, frotz can turn those off: enter \mp 0 as a command.

**Comment by lemmy04** [comment]
oh and you want to /save your game frequently - my container that this runs in gets restarted a few times per week,

**Comment by RattyDAVE** [comment]
Have you got instructions on how you made this?

**Comment by lemmy04** [comment]
https://www.tuxonline.tech/index.php/2021/04/21/from-0-to-kubernetes-step-8-are-you-ready-player-one/ :)

**Comment by lemmy04** [comment]
by the way: https://hub.docker.com/repository/docker/lemmy04/h3270/
