### ISSUE TITLE
GCOS?

### ISSUE THREAD

**Issue by d0325mgray** [RattyDAVE/docker-ubuntu-hercules-mvs#6]
Not really an MVS issue but is the an emulation planned for the Honeywell GCOS?

Sorry, I don't know how to send questions in GitHub

**Comment by RattyDAVE** [comment]
Sorry I keep looking for the TAPES unable to find them. 

If you have any better luck than me please let me know and ill see what I can do. 

If I do find it then I will add to https://hub.docker.com/r/rattydave/alpine-simh/
